// Code generated by Prismic. DO NOT EDIT.

import Callout from "./Callout";
import CodeSnippet from "./CodeSnippet";
import Media from "./Media";
import Related from "./Related";
import RichText from "./RichText";

export const components = {
	callout: Callout,
	code_snippet: CodeSnippet,
	media: Media,
	related: Related,
	rich_text: RichText
};